### ISSUE TITLE
I have a problem compiling

### ISSUE THREAD

**Issue by staffnetDev** [zfl9/dns2tcp#10]
![image](https://user-images.githubusercontent.com/34721370/148469360-1147eca2-c39a-417c-8fda-3b05e9628bf2.png)

**Comment by zfl9** [comment]
https://github.com/zfl9/dns2tcp/blob/10ed687778f18d1b9c98bb51187a3a9086d3a0d9/libev/mylite.h#L11

change 0 to 1

**Comment by zfl9** [comment]
Try to add this line to libev/mylite.h
```c
#define EV_USE_CLOCK_SYSCALL 1
```

**Comment by staffnetDev** [comment]
I want to ask you if there is a way to compile in ndk to use it in android.

**Comment by zfl9** [comment]
I haven't tried it in the ndk, I'll try it at the weekend

**Comment by staffnetDev** [comment]
I thank you I hope !!
