### ISSUE TITLE
此插件编译失败

### ISSUE THREAD

**Issue by bobandbrony** [zfl9/dns2tcp#14]
使用的是https://github.com/P3TERX/Actions-OpenWrt
在线编译
报错内容
make[4]: Entering directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
mipsel-openwrt-linux-musl-gcc -std=c99 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1=dns2tcp-1.1.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -c libev/ev.c -o libev/ev.o
libev/ev.c:2139:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^~~~~~~~~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:4260: Error: opcode not supported on this processor: mips2 (mips2) `sync'
{standard input}:4535: Error: opcode not supported on this processor: mips2 (mips2) `sync'
make[4]: *** [Makefile:25: libev/ev.o] Error 1
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
make[3]: *** [Makefile:45: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/small/dns2tcp'
time: package/feeds/small/dns2tcp/compile#0.35#0.07#0.39
    ERROR: package/feeds/small/dns2tcp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/dns2tcp/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by zfl9** [comment]
编译参数改一下，见 #13

**Comment by bobandbrony** [comment]
> 编译参数改一下，见 #13

em我不知道怎么做

**Comment by zfl9** [comment]
你把makefile打开，找到cflags相关的，增加参数 -fno-mips16 ，试试看？

**Comment by bobandbrony** [comment]
> 你把makefile打开，找到cflags相关的，增加参数 -fno-mips16 ，试试看？

我用的是这个在线编译https://github.com/bobandbrony/OpenWrt-
没有这些文件

**Comment by bobandbrony** [comment]
本地编译成功了，只需要在这里
![image](https://github.com/zfl9/dns2tcp/assets/129247570/15e236de-1b9e-4398-87a0-37f7f82292b5)
结果
![image](https://github.com/zfl9/dns2tcp/assets/129247570/1f612e70-15de-4fe8-a1e2-3ee5b4e1ecc0)
