### ISSUE TITLE
请问可以屏蔽AAAA的返回记录吗？

### ISSUE THREAD

**Issue by MeIsReallyBa** [zfl9/dns2tcp#3]
现在用于路由器上专门解析GFWLIST，虽然dnsmasq可以手动屏蔽指定域名的V6，但是规则多了感觉性能有点下降，不知道能不能把屏蔽V6做到dns2tcp上。。。

**Comment by zfl9** [comment]
dns2tcp只打算实现 udp2tcp 功能，不打算做其他事情。
