### ISSUE TITLE
ubuntu 18.04安装不了，求指导

### ISSUE THREAD

**Issue by jayceyang** [zfl9/dns2tcp#4]
make && sudo make install后报错，如下：

gcc -w -O2 -c libev/ev.c -o ev.o
make: gcc: Command not found
Makefile:31: recipe for target 'ev.o' failed
make: *** [ev.o] Error 127

**Comment by zfl9** [comment]
你没安装gcc编译环境。

**Comment by jayceyang** [comment]
是的。可是安装不上，不知道怎么办：

<img width="573" alt="image" src="https://user-images.githubusercontent.com/2830415/77034667-78014d80-69e5-11ea-984c-c03c95de0cef.png">

**Comment by jayceyang** [comment]
图片可能显示不出来，我贴错误信息：

sudo apt install gcc
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 gcc : 依赖: gcc-7 (>= 7.3.0-12~) 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

**Comment by zfl9** [comment]
这个问题与dns2tcp无关，建议去ubuntu社区问下。或者百度谷歌如何解决。我也不了解ubuntu

**Comment by jayceyang** [comment]
谢谢大大
