### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by peyoot** [zfl9/dns2tcp#7]
Is there any released binary for win10 64bit? or a workable project for compiling?

**Comment by pexcn** [comment]
Try this: [dns2tcp.zip](https://github.com/zfl9/dns2tcp/files/4721176/dns2tcp.zip)

**Comment by zfl9** [comment]
不熟悉win编程。

**Comment by zfl9** [comment]
不过 cygwin 应该能编译。具体也没试过。
