### ISSUE TITLE
[Suggestion] Inverse mode

### ISSUE THREAD

**Issue by phantomcraft** [zfl9/dns2tcp#8]
I want to forward a DNS port to a container in TCP format, but I couldn't find any program on Github that forwards DNS queries on UDP port and provides a TCP port for listening.

This mode would be like this:

[Remote UDP DNS address#port] <===> [dns2tcp] <===> [Listening TCP DNS address#port]

There is no program that make this possible yet, so I am requesting this.

**Comment by zfl9** [comment]
Are you trying to say: dns-tcp2udp ?

**Comment by phantomcraft** [comment]
dns-udp2tcp

Resolve UDP, Listen TCP.

**Comment by zfl9** [comment]
> dns-udp2tcp
> 
> Resolve UDP, Listen TCP.

???Don't understand the specific meaning
